import type {Metadata} from 'next';
import type {PropsWithChildren} from 'react';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const RootLayout: React.FC<PropsWithChildren<never>> = ({children}) => {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
